cloud:
  aws:
    credentials:
      access-key: <<secret-key>>
      secret-key: <secret-access-key>
    region:
      us-east-1
    stack:
      auto: false

application:
  bucket:
    name: jawahar-bucket
